spring:
  application:
    name: eproc-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/eproc_db
    username: postgres
    password: complex26
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

logging:
  level:
    root: INFO
    org.springframework.web: INFO

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:b50492e3aceb859392141ee7681353c8a1ef9e891085e554175ec75491547b79}
  expiration: ${JWT_EXPIRATION:900000} # 15 minutes
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 days
  cookie-name: eproc-jwt
  refresh-cookie-name: eproc-refresh-jwt
